[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "stustapay"
license = { file = "LICENSE" }
dynamic = ["version"]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 (AGPLv3)",
]
requires-python = ">=3.9"
dependencies = [
    "fastapi==0.95.1",
    "python-multipart==0.0.6",
    "uvicorn[standard]==0.22.0",
    "passlib[bcrypt]==1.7.4",
    "asyncpg==0.27.0",
    "PyYAML==6.0",
    "python-jose[cryptography]==3.3.0",
    "Jinja2==3.1.2",
    "aiohttp==3.8.4",
    "pylatexenc==2.10",
    "schwifty==2023.3.0",
    "sepaxml==2.6.1",
    "types-python-dateutil==2.8.19.13",
    "types-pytz==2023.3.0.0"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "black",
    "mypy",
    "pylint",
    "types-PyYAML",
]

[project.urls]
Source = "https://github.com/stustanet/stustapay"

[tool.setuptools.packages.find]
#where = [""]
namespaces = false
#include = ["stustapay*"]
exclude = ["stustapay.tests*", "tests*"]

[tool.pylint]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "fixme",
    "logging-fstring-interpolation",
    "unspecified-encoding",
    "broad-exception-raised",
    "broad-exception-caught"
]

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.mypy]
ignore_missing_imports = true
# check_untyped_defs = true # TODO: enable ass soon as the checks would pass
pretty = true
plugins = [
    "pydantic.mypy"
]

[tool.coverage.run]
source = [
    "stustapay"
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "stustapay.tests",
]
