[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "stustapay"
license = { file = "LICENSE" }
dynamic = ["version"]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 (AGPLv3)",
]
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "passlib[bcrypt]",
    "asyncpg",
    "PyYAML",
    "python-jose[cryptography]",
    "jinja2",
    "pylatexenc"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
dev = [
    "black",
    "mypy",
    "pylint",
    "types-PyYAML",
]

[project.urls]
Source = "https://github.com/stustanet/stustapay"

[tool.setuptools]
packages = ["stustapay"]

[tool.pylint]
extension-pkg-whitelist = [
    "pydantic"
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    "C",
    "R",
    "fixme",
    "logging-fstring-interpolation",
    "unspecified-encoding",
    "broad-exception-raised",
]

[tool.black]
line-length = 120
target-version = ["py39"]

[tool.mypy]
ignore_missing_imports = true
pretty = true
plugins = [
    "pydantic.mypy"
]

[tool.coverage.run]
source = [
    "stustapay"
]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "stustapay.tests",
]